### PR TITLE
Update README with snippets and information

### PR DESCRIPTION
**Pull request by CameronDiver**
Change-type: patch
Signed-off-by: Cameron Diver <cameron@resin.io>

### CODE REVIEW

**Comment by CameronDiver** [comment]
@shaunmulligan It does, there's an example here: https://github.com/resin-io-playground/node-sense-hat/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R155

**Comment by shaunmulligan** [comment]
Ah, I just didn't see it mentioned in the readme so assumed it might not be implemented.

**Comment by CameronDiver** [comment]
Do you mean in this README updates? I added a small bit at the top here: https://github.com/resin-io-playground/node-sense-hat/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R4 but can make it more prominent if you like?

**Comment by shaunmulligan** [comment]
yeah, I just noticed there wasn't any example usage for those sensors, but there were some for the the others.

**Pull request merged**
